#!/usr/bin/env bash
#
# Build nec2++ as a WebAssembly ES module.
#
# Compiles the nec2++ submodule (third_party/necpp) together with the embind
# facade in src/binding.cpp, and emits:
#   prebuilts/nec2pp.mjs        + prebuilts/nec2pp.wasm   (separate .wasm)
#   prebuilts/nec2pp-inline.mjs                           (.wasm embedded)
#
# Upstream's own CMake wasm target is deliberately not used. It builds a stub
# wrapper that reads stdin, and it omits -fexceptions, without which nothing it
# produces can finish a solve (see below). Calling emcc directly is also what
# the sibling nec2c-wasm package does, so the two builds stay comparable.

set -euo pipefail

# Pinned toolchain, matching nec2c-wasm. The committed artifacts only reproduce
# against this version.
EMCC_VERSION=6.0.3

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$here/../.." && pwd)"
vendor="$here/third_party/necpp"
outdir="$here/prebuilts"
emsdk="$repo_root/emsdk"

if [ ! -f "$vendor/src/nec_context.cpp" ]; then
  echo "error: the nec2++ submodule is not checked out." >&2
  echo "       run: git submodule update --init" >&2
  exit 1
fi

emcc_version() { emcc --version 2>/dev/null | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1; }

if [ "$(emcc_version)" != "$EMCC_VERSION" ]; then
  if [ ! -f "$emsdk/emsdk" ]; then
    echo "error: emcc $EMCC_VERSION not on PATH and the emsdk submodule is missing." >&2
    echo "       run: git submodule update --init" >&2
    exit 1
  fi
  "$emsdk/emsdk" install "$EMCC_VERSION"
  "$emsdk/emsdk" activate "$EMCC_VERSION"
  # shellcheck disable=SC1091
  source "$emsdk/emsdk_env.sh" >/dev/null 2>&1
fi

if [ "$(emcc_version)" != "$EMCC_VERSION" ]; then
  echo "error: emcc is $(emcc_version), expected $EMCC_VERSION." >&2
  exit 1
fi

mkdir -p "$outdir"

# nec2++ library sources, from NECPP_LIB_SRCS in src/CMakeLists.txt. XGetopt
# and the nec2cpp/necDiff mains are command-line plumbing and are left out.
sources=(
  c_evlcom.cpp
  c_geometry.cpp
  c_ggrid.cpp
  c_plot_card.cpp
  electromag.cpp
  libNEC.cpp
  matrix_algebra.cpp
  misc.cpp
  nec_context.cpp
  nec_exception.cpp
  nec_ground.cpp
  nec_output.cpp
  nec_radiation_pattern.cpp
  nec_results.cpp
  nec_structure_currents.cpp
)

srcpaths=("$here/src/binding.cpp")
for s in "${sources[@]}"; do
  srcpaths+=("$vendor/src/$s")
done

# nec2++ includes a generated config.h holding only a version string and a
# build date. CMake writes it; we supply it directly so the build needs no
# configure step. The date comes from the pinned submodule commit rather than
# from the clock, so rebuilding the same commit produces the same bytes.
gendir="$here/build"
mkdir -p "$gendir"
necpp_version="$(grep -oE 'VERSION[[:space:]]+[0-9]+\.[0-9]+\.[0-9]+' "$vendor/CMakeLists.txt" | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')"
necpp_date="$(git -C "$vendor" log -1 --format=%cs)"
cat > "$gendir/config.h" <<EOF
#ifndef CONFIG_H
#define CONFIG_H
/* Generated by build.sh; nec2++ only reads a version and a date from here. */
#define NECPP_VERSION "$necpp_version"
#define NECPP_BUILD_DATE "$necpp_date"
#endif /* CONFIG_H */
EOF

# -fexceptions is not optional. nec2++ uses exceptions for control flow, not
# only for errors: nec_context ends a single-frequency run by throwing to
# unwind to the card-input loop. Compiled without exception support the
# matching catch is elided, so every completed solve escapes as an uncaught
# error. It has to be a compile flag as well as a link one -- the link flag
# cannot restore a catch already dropped from the objects.
common_flags=(
  -std=c++17
  -O2
  -fexceptions
  -I"$vendor/src"
  -I"$gendir"
  -isystem "$vendor/src/eigen"
  --bind
  -sMODULARIZE=1
  -sEXPORT_ES6=1
  -sEXPORT_NAME=createNec2pp
  -sALLOW_MEMORY_GROWTH=1
  -sENVIRONMENT=web,node
)

emcc "${common_flags[@]}" "${srcpaths[@]}" -o "$outdir/nec2pp.mjs"

# SINGLE_FILE embeds the wasm as base64 in the glue, for bundlers that will not
# emit or serve a sibling .wasm.
emcc "${common_flags[@]}" -sSINGLE_FILE=1 "${srcpaths[@]}" -o "$outdir/nec2pp-inline.mjs"

# emcc marks the .wasm executable; it is data, and the committed mode is 0644.
chmod 644 "$outdir/nec2pp.wasm"

echo "built nec2++ $necpp_version with emcc $EMCC_VERSION:"
ls -l "$outdir/nec2pp.mjs" "$outdir/nec2pp.wasm" "$outdir/nec2pp-inline.mjs"
